[workspace]
authors = ["Doug Latornell <dlatornell@eoas.ubc.ca>"]
channels = ["conda-forge"]
name = "moad-docs"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
repository = "https://github.com/UBC-MOAD/docs"
documentation = "https://ubc-moad-docs.readthedocs.io/en/latest/"

[tasks]

[dependencies]
python = "3.14.*"
# For repo QA
pip = "*"
pre-commit = "*"
# For building the docs
nbsphinx = "==0.9.5"
sphinx = "==8.1.3"
sphinx-notfound-page = "==1.0.4"
sphinx-rtd-theme = "==3.0.0"

[pypi-dependencies]
# For build on readthedocs
commonmark = ">=0.9.1, <0.10"
recommonmark = ">=0.7.1, <0.8"
readthedocs-sphinx-ext = ">=2.2.5, <3"
